предварительно готовое дз
Dymoc/advanced_js pull request #2
Opened 2020-08-22 10:10 UTC by Dymoc

2020-08-24 13:35 UTC, Om1X requested changes

2020-08-24 13:35 UTC, Om1X commented on src/js/cart.js
> +        this.totalQuantity = null;
Лишние свойства. Эти данные можно получать через методы.

2020-08-24 13:35 UTC, Om1X commented on src/js/cart.js
> +    };
заменить работу со свойствами на внутреннюю переменную метода и в ней сакумулировать значение и вернуть.

2020-08-25 07:21 UTC, Dymoc commented
Правки внесены

2020-08-26 10:44 UTC, merged